name = "GithubRegistries"
uuid = "5675c7fe-ba7c-4363-918a-7ca75c940b6a"
repo = "https://github.com/izawakazuhiko/JuliaRegistries.git"

[packages]
a42d1af7-8a3f-4cb0-91e8-bffbe95c7eba = { name = "MATXS", path = "M/MATXS" }
